all:
	rm -f main
	clear
	g++ "../01_aufgabe/image.cpp" shape.cpp shapecontainer.cpp rectangle.cpp triangle.cpp circle.cpp main.cpp -o main -std=c++11 
	./main && open -a Preview output.pgm

main: all
